# .devcontainer/Dockerfile
FROM vcp-diplay-embedded-base:latest

USER root

# RUN apt-get update && apt-get install -y --no-install-recommends \
#     pkg1 \
#     pkg2 \
#     pkg3

# RUN pip install pkg1 pkg2

# Use the same user as base
USER devuser
WORKDIR /home/devuser/workspace