# .devcontainer/Dockerfile
FROM vcp-diplay-desktop-base:latest

USER root

# RUN apt-get update && apt-get install -y --no-install-recommends \
#         nano \
#         pkg-config \
#         minicom

# RUN pip install pyserial

# Use the same user as base
USER devuser
WORKDIR /home/devuser/workspace